[package]
name = "bevy_mod_mdl"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder.workspace = true
chrono.workspace = true
thiserror.workspace = true
bevy_math.workspace = true
bevy_log.workspace = true
seismon-utils.workspace = true
num-traits.workspace = true
