unstable_features = true

use_small_heuristics = "Max"

comment_width = 100
wrap_comments = true
normalize_comments = true

where_single_line = true
brace_style = "PreferSameLine"
newline_style = "Unix"

imports_granularity = "Crate"
